global:
  scrape_interval: 15s
  evaluation_interval: 15s

storage:
  exemplars:
    max_exemplars: 100000

remote_write: []

scrape_configs:
  - job_name: binoc
    metrics_path: /metrics
    scrape_protocols: ["OpenMetricsText1.0.0", "PrometheusText0.0.4"]
    static_configs:
      - targets: ["app:8080"]

  - job_name: caddy
    metrics_path: /metrics
    static_configs:
      - targets: ["caddy:2019"]
